conventions:
  x_key: x
  y_key: y
core:
  entity: gladia
  project_name: task-vectors-playground
  storage_dir: ${oc.env:PROJECT_ROOT}/storage
  tags:
  - dev
  version: 0.0.1
defaults:
- hydra: default
- nn: default
- train: default
- _self_
epoch_divisor: None
eval_datasets:
- CIFAR100
- DTD
- EuroSAT
- GTSRB
- MNIST
- RESISC45
- SVHN
eval_on_train: false
misc:
  cache_dir: null
  ckpt_path: ${oc.env:PROJECT_ROOT}/checkpoints/${nn.module.model.model_name}
  openclip_cachedir: ${oc.env:PROJECT_ROOT}/checkpoints/openclip_cache
  pretrained_checkpoint: ${misc.ckpt_path}/zeroshot.pt
order: 1
seed_index: 0
task_vectors:
  aggregator:
    _target_: tvp.task_vectors.aggregator.SumAggregator
    mean: true
  breadcrumbs_beta: 0.85
  breadcrumbs_gamma: 0.993
  merging_method: breadcrumbs
  num_task_vectors: 8
  orthogonalize: false
  scaling_coefficient: 1
  ties_lambda: 1
  ties_topk: 0.2
  to_apply:
  - CIFAR100
  - DTD
  - EuroSAT
  - GTSRB
  - MNIST
  - RESISC45
  - SVHN
