core:
  project_name: task-vectors-playground
  storage_dir: ${oc.env:PROJECT_ROOT}/storage
  entity: gladia
  version: 0.0.1
  tags:
    - dev

defaults:
  - hydra: default
  - nn: default
  - train: default
  - _self_ # as last argument to allow the override of parameters via this main config

seed_index: 0
eval_on_train: false

conventions:
  x_key: 'x'
  y_key: 'y'

eval_datasets:
  #- Cars
  - CIFAR100
  - DTD
  - EuroSAT
  - GTSRB
  - MNIST
  - RESISC45
  - SVHN

task_vectors:
  to_apply:
  # - Cars
    - CIFAR100
    - DTD
    - EuroSAT
    - GTSRB
    - MNIST
    - RESISC45
    - SVHN
    
  orthogonalize: false

  scaling_coefficient: 1
  num_task_vectors: 8
  
  aggregator:
    # _target_: tvp.task_vectors.aggregator.SphericalAggregator
    _target_: tvp.task_vectors.aggregator.SumAggregator
    mean: true


misc:
  ckpt_path: ${oc.env:PROJECT_ROOT}/checkpoints/${nn.module.model.model_name}
  pretrained_checkpoint: ${misc.ckpt_path}/zeroshot.pt
  openclip_cachedir: "${oc.env:PROJECT_ROOT}/checkpoints/openclip_cache"
  cache_dir: null

epoch_divisor: 2 # the actual number of epochs is the original number divided by this coefficient, here we need to indicate this for evaluation
order: 5