_target_: tvp.modules.clip_text_encoder.ClipTextEncoder
model_name: ViT-B-16 # ViT-B-16, ViT-L-14
openclip_cachedir: ${misc.openclip_cachedir}
cache_dir: ${misc.cache_dir}
x_key: ${conventions.x_key}
y_key: ${conventions.y_key}
hidden_size: 512 # 512 for ViT-B-16, 768 for ViT-L-14