
defaults:
  - _self_
  - model: clip_text_encoder

_target_: tvp.pl_module.text_classifier.TextClassifier
x_key: ${conventions.x_key}
y_key: ${conventions.y_key}
attn_mask_key: ${conventions.attn_mask_key} # put this in bert.yml
encoder: ??
classifier: ??

optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-5
  # _target_: torch.optim.SGD
  # lr: 0.001
  # momentum: 0
  # weight_decay: 0

# lr_scheduler:
#   _target_: pl_bolts.optimizers.lr_scheduler.LinearWarmupCosineAnnealingLR
#   warmup_epochs: 5
#   max_epochs: ${train.trainer.max_epochs}
#   warmup_start_lr: 1e-6
#   eta_min: 0.0
#   last_epoch: -1
